# -*- coding: utf-8 -*-
"""modelo_bert-base.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sI8a_tY7zMZUrqc9GY6fSy3NzDZeMcgc
"""

import pandas as pd
from transformers import AutoTokenizer, AutoModelForTokenClassification
import requests

tokenizer = AutoTokenizer.from_pretrained("dccuchile/bert-base-spanish-wwm-uncased-finetuned-ner")
model = AutoModelForTokenClassification.from_pretrained("dccuchile/bert-base-spanish-wwm-uncased-finetuned-ner")

import requests

API_URL = "https://api-inference.huggingface.co/models/dccuchile/bert-base-spanish-wwm-uncased-finetuned-ner"
headers = {"Authorization": "Bearer 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"}

def query(payload):
	response = requests.post(API_URL, headers=headers, json=payload)
	return response.json()
# Carga el archivo csv
df = pd.read_csv('/content/drive/MyDrive/ecuPrueba.csv')
# Itera sobre cada fila del dataframe
for index, row in df.iterrows():
    # Realiza la consulta
    output = query({"inputs": row['ATA_TEXTO']})

   # Imprime el ID de la llamada una vez
    print(f"ID LLAMADA: {row['TRA_ID']}")

 # Procesa la salida
    for entity in output:
        # Filtra por tipo 'LABEL_0'
        if entity['entity_group'] != 'LABEL_0':
            print(f"Entidad: {entity['word']}, Tipo: {entity['entity_group']}, Confianza: {entity['score']}")